# Generated by Django 5.1.3 on 2024-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('total_distance', models.FloatField(help_text='Mesafe (km cinsinden)')),
                ('total_duration', models.FloatField(help_text='Süre (dakika cinsinden)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rota Geçmişi',
                'verbose_name_plural': 'Rota Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
