# Generated by Django 5.1.2 on 2024-12-27 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(default='', max_length=255)),
                ('end_address', models.CharField(default='', max_length=255)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('total_distance', models.FloatField(help_text='Mesafe (km cinsinden)')),
                ('total_duration', models.FloatField(help_text='Süre (dakika cinsinden)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rota Geçmişi',
                'verbose_name_plural': 'Rota Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
