# Generated by Django 5.1.3 on 2024-12-07 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routehistory',
            name='end_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='routehistory',
            name='start_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='routehistory',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
