# Generated by Django 5.1.2 on 2024-10-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='araclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_adi', models.CharField(max_length=100)),
                ('ortalama_menzil', models.IntegerField(max_length=8)),
                ('max_menzil', models.IntegerField(max_length=8)),
                ('min_menzil', models.IntegerField(max_length=8)),
            ],
        ),
    ]
