# Generated by Django 5.1.2 on 2024-10-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='İletişim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=14)),
                ('mail', models.CharField(max_length=70)),
                ('faks', models.CharField(max_length=20)),
                ('adres', models.CharField(max_length=200)),
            ],
        ),
    ]
