# Generated by Django 5.1.2 on 2024-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='osm_id',
            field=models.CharField(default='default_osm_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
