# Generated by Django 5.1.2 on 2024-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0002_chargingstation_osm_id_alter_chargingstation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='osm_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
