# Generated by Django 5.1.2 on 2024-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0003_chargingstation_address_chargingstation_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
