# Generated by Django 5.1.2 on 2024-11-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0004_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default=38.6761),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default=39.2234),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
