# Generated by Django 5.1.2 on 2024-11-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0005_restaurant_latitude_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
