# Generated by Django 5.1.2 on 2024-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0007_chargingstation_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='place_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
